version: '3.6'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
      - mongo-data:/data/db
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine
    volumes:
      - ./server:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
    ports:
      - 127.0.0.1:3000:3000
    command: npm start

volumes:
  mongo-data: {}
